amazon:
  # 以下3行はそのまま
  service: S3
  access_key_id: <%= Rails.application.credentials.dig(:aws, :access_key_id) %>
  secret_access_key: <%= Rails.application.credentials.dig(:aws, :secret_access_key) %>
  # 以下２行は変える
  region: ap-northeast-1 #東京
  bucket: my-rails-portfolio-app-bucket #自分で作成したS3のバケットの名前